name: '@zju-health-report/action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    # 可以参考 https://crontab.guru/ 进行配置
    - cron: '0 23 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME4
            password: ZJU_PASSWORD4
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME5
            password: ZJU_PASSWORD5
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME6
            password: ZJU_PASSWORD6
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME7
            password: ZJU_PASSWORD7
            dingtalk_token: DINGTALK_TOKEN
          - username: ZJU_USERNAME8
            password: ZJU_PASSWORD8
            dingtalk_token: DINGTALK_TOKEN
    steps:
      - name: 打卡
        uses: zju-health-report/action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
        env:
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
